classes:
  0:
  - Wearing
  - Male
  - Under 30
  1:
  - Wearing
  - Male
  - Between 30 and 60
  2:
  - Wearing
  - Male
  - Over 60
  3:
  - Wearing
  - Female
  - Under 30
  4:
  - Wearing
  - Female
  - Between 30 and 60
  5:
  - Wearing
  - Female
  - Over 60
  6:
  - Incorrectly Wearing
  - Male
  - Under 30
  7:
  - Incorrectly Wearing
  - Male
  - Between 30 and 60
  8:
  - Incorrectly Wearing
  - Male
  - Over 60
  9:
  - Incorrectly Wearing
  - Female
  - Under 30
  10:
  - Incorrectly Wearing
  - Female
  - Between 30 and 60
  11:
  - Incorrectly Wearing
  - Female
  - Over 60
  12:
  - Not Wearing
  - Male
  - Under 30
  13:
  - Not Wearing
  - Male
  - Between 30 and 60
  14:
  - Not Wearing
  - Male
  - Over 60
  15:
  - Not Wearing
  - Female
  - Under 30
  16:
  - Not Wearinging
  - Female
  - Between 30 and 60
  17:
  - Not Wearing
  - Female
  - Over 60
model_path: /home/limepencil/Boostcamp-AI-Tech-Product-Serving/streamlit_prototyping_special_mission_1/model_pretrained.ckpt
hparam_path: /home/limepencil/Boostcamp-AI-Tech-Product-Serving/streamlit_prototyping_special_mission_1/hparams.yaml